<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20200613072502 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'postgresql', 'Migration can only be executed safely on \'postgresql\'.');

        $this->addSql('CREATE TABLE emails (id SERIAL NOT NULL, person_id INT NOT NULL, created_by_id INT NOT NULL, address VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_4C81E852217BBB47 ON emails (person_id)');
        $this->addSql('CREATE INDEX IDX_4C81E852B03A8386 ON emails (created_by_id)');
        $this->addSql('CREATE TABLE civilities (id SERIAL NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE marital_status (id SERIAL NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE persons (id SERIAL NOT NULL, sex_id INT NOT NULL, created_by_id INT DEFAULT NULL, civility_id INT NOT NULL, marital_status_id INT NOT NULL, last_name VARCHAR(255) NOT NULL, born_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, postal VARCHAR(255) DEFAULT NULL, slug VARCHAR(255) NOT NULL, address VARCHAR(255) DEFAULT NULL, birth_place VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_A25CC7D35A2DB2A0 ON persons (sex_id)');
        $this->addSql('CREATE INDEX IDX_A25CC7D3B03A8386 ON persons (created_by_id)');
        $this->addSql('CREATE INDEX IDX_A25CC7D323D6A298 ON persons (civility_id)');
        $this->addSql('CREATE INDEX IDX_A25CC7D3E559F9BF ON persons (marital_status_id)');
        $this->addSql('CREATE TABLE "users" (id SERIAL NOT NULL, person_id INT DEFAULT NULL, user_name VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, is_blocked BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E924A232CF ON "users" (user_name)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9217BBB47 ON "users" (person_id)');
        $this->addSql('CREATE TABLE sexes (id SERIAL NOT NULL, sex_name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE blood_groups (id SERIAL NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE patients (id SERIAL NOT NULL, person_id INT NOT NULL, created_by_id INT NOT NULL, blood_group_id INT DEFAULT NULL, save_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_2CCC2E2CB03A8386 ON patients (created_by_id)');
        $this->addSql('CREATE INDEX IDX_2CCC2E2C5F3AECE2 ON patients (blood_group_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2CCC2E2C217BBB47 ON patients (person_id)');
        $this->addSql('CREATE TABLE cashiers (id SERIAL NOT NULL, person_id INT NOT NULL, created_by_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_EE44F633217BBB47 ON cashiers (person_id)');
        $this->addSql('CREATE INDEX IDX_EE44F633B03A8386 ON cashiers (created_by_id)');
        $this->addSql('CREATE TABLE nurses_categories (id SERIAL NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE nurses (id SERIAL NOT NULL, person_id INT NOT NULL, category_id INT DEFAULT NULL, created_by_id INT NOT NULL, save_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_F409A14C12469DE2 ON nurses (category_id)');
        $this->addSql('CREATE INDEX IDX_F409A14CB03A8386 ON nurses (created_by_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F409A14C217BBB47 ON nurses (person_id)');
        $this->addSql('CREATE TABLE doctors (id SERIAL NOT NULL, person_id INT NOT NULL, category_id INT DEFAULT NULL, created_by_id INT NOT NULL, save_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_B67687BE12469DE2 ON doctors (category_id)');
        $this->addSql('CREATE INDEX IDX_B67687BEB03A8386 ON doctors (created_by_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B67687BE217BBB47 ON doctors (person_id)');
        $this->addSql('CREATE TABLE doctors_categories (id SERIAL NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE others_types_staff (id SERIAL NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE others_staff (id SERIAL NOT NULL, person_id INT NOT NULL, type_staff_id INT DEFAULT NULL, created_by_id INT NOT NULL, comment VARCHAR(255) DEFAULT NULL, save_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_F14D76FEC0B27031 ON others_staff (type_staff_id)');
        $this->addSql('CREATE INDEX IDX_F14D76FEB03A8386 ON others_staff (created_by_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F14D76FE217BBB47 ON others_staff (person_id)');
        $this->addSql('CREATE TABLE technicians_categories (id SERIAL NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE technicians (id SERIAL NOT NULL, person_id INT NOT NULL, category_id INT DEFAULT NULL, created_by_id INT NOT NULL, save_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_63FB424012469DE2 ON technicians (category_id)');
        $this->addSql('CREATE INDEX IDX_63FB4240B03A8386 ON technicians (created_by_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_63FB4240217BBB47 ON technicians (person_id)');
        $this->addSql('CREATE TABLE phone_numbers (id SERIAL NOT NULL, person_id INT NOT NULL, created_by_id INT NOT NULL, value VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, comment VARCHAR(255) DEFAULT NULL, is_use BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_E7DC46CB217BBB47 ON phone_numbers (person_id)');
        $this->addSql('CREATE INDEX IDX_E7DC46CBB03A8386 ON phone_numbers (created_by_id)');
        $this->addSql('CREATE TABLE first_names (id SERIAL NOT NULL, person_id INT NOT NULL, created_by_id INT NOT NULL, value VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_D3704F4A217BBB47 ON first_names (person_id)');
        $this->addSql('CREATE INDEX IDX_D3704F4AB03A8386 ON first_names (created_by_id)');
        $this->addSql('CREATE TABLE identity_cards (id SERIAL NOT NULL, person_id INT NOT NULL, created_by_id INT NOT NULL, identity_number INT NOT NULL, comment VARCHAR(255) DEFAULT NULL, issue_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expiration_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, actual_card BOOLEAN DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_EE99120D217BBB47 ON identity_cards (person_id)');
        $this->addSql('CREATE INDEX IDX_EE99120DB03A8386 ON identity_cards (created_by_id)');
        $this->addSql('CREATE TABLE payments (id SERIAL NOT NULL, created_by_id INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, reference VARCHAR(255) NOT NULL, comment TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_65D29B32B03A8386 ON payments (created_by_id)');
        $this->addSql('CREATE TABLE advance_payments (id SERIAL NOT NULL, payment_id INT NOT NULL, created_by_id INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, amount DOUBLE PRECISION NOT NULL, comment TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_E098C60C4C3A3BB ON advance_payments (payment_id)');
        $this->addSql('CREATE INDEX IDX_E098C60CB03A8386 ON advance_payments (created_by_id)');
        $this->addSql('CREATE TABLE lab_tests_categories (id SERIAL NOT NULL, created_by_id INT NOT NULL, wording VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_D645F012B03A8386 ON lab_tests_categories (created_by_id)');
        $this->addSql('CREATE TABLE lab_tests (id SERIAL NOT NULL, created_by_id INT NOT NULL, category_id INT NOT NULL, code VARCHAR(255) NOT NULL, wording VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_75AC2A9677153098 ON lab_tests (code)');
        $this->addSql('CREATE INDEX IDX_75AC2A96B03A8386 ON lab_tests (created_by_id)');
        $this->addSql('CREATE INDEX IDX_75AC2A9612469DE2 ON lab_tests (category_id)');
        $this->addSql('CREATE TABLE lab_tests_requested (id SERIAL NOT NULL, patient_id INT NOT NULL, created_by_id INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, comment TEXT DEFAULT NULL, is_urgent BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_4D16476E6B899279 ON lab_tests_requested (patient_id)');
        $this->addSql('CREATE INDEX IDX_4D16476EB03A8386 ON lab_tests_requested (created_by_id)');
        $this->addSql('CREATE TABLE lab_tests_ranges (id SERIAL NOT NULL, lab_test_id INT NOT NULL, created_by_id INT NOT NULL, wording VARCHAR(255) DEFAULT NULL, min_value VARCHAR(255) NOT NULL, max_value VARCHAR(255) NOT NULL, unit VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_2EB7118972CE4932 ON lab_tests_ranges (lab_test_id)');
        $this->addSql('CREATE INDEX IDX_2EB71189B03A8386 ON lab_tests_ranges (created_by_id)');
        $this->addSql('CREATE TABLE lab_test_model_rates (id SERIAL NOT NULL, lab_test_model_id INT NOT NULL, created_by_id INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, rate DOUBLE PRECISION NOT NULL, is_actual BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_E8515BB0C07EA3DE ON lab_test_model_rates (lab_test_model_id)');
        $this->addSql('CREATE INDEX IDX_E8515BB0B03A8386 ON lab_test_model_rates (created_by_id)');
        $this->addSql('CREATE TABLE lab_test_models_requested (id SERIAL NOT NULL, patient_id INT NOT NULL, created_by_id INT NOT NULL, lab_test_model_rate_id INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, comment TEXT DEFAULT NULL, is_urgent BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_4E74C6186B899279 ON lab_test_models_requested (patient_id)');
        $this->addSql('CREATE INDEX IDX_4E74C618B03A8386 ON lab_test_models_requested (created_by_id)');
        $this->addSql('CREATE INDEX IDX_4E74C61896121641 ON lab_test_models_requested (lab_test_model_rate_id)');
        $this->addSql('CREATE TABLE lab_test_model_details (id SERIAL NOT NULL, lab_test_model_id INT NOT NULL, created_by_id INT NOT NULL, lab_test_id INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_58AD8254C07EA3DE ON lab_test_model_details (lab_test_model_id)');
        $this->addSql('CREATE INDEX IDX_58AD8254B03A8386 ON lab_test_model_details (created_by_id)');
        $this->addSql('CREATE INDEX IDX_58AD825472CE4932 ON lab_test_model_details (lab_test_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_58AD825472CE4932C07EA3DE ON lab_test_model_details (lab_test_id, lab_test_model_id)');
        $this->addSql('CREATE TABLE lab_test_models_requested_details (id SERIAL NOT NULL, lab_test_model_requested_id INT NOT NULL, lab_test_model_detail_id INT NOT NULL, lab_test_cost_id INT NOT NULL, payment_id INT DEFAULT NULL, lab_test_model_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_718DC327BCA92477 ON lab_test_models_requested_details (lab_test_model_requested_id)');
        $this->addSql('CREATE INDEX IDX_718DC327530FFA25 ON lab_test_models_requested_details (lab_test_model_detail_id)');
        $this->addSql('CREATE INDEX IDX_718DC327707FB509 ON lab_test_models_requested_details (lab_test_cost_id)');
        $this->addSql('CREATE INDEX IDX_718DC3274C3A3BB ON lab_test_models_requested_details (payment_id)');
        $this->addSql('CREATE INDEX IDX_718DC327C07EA3DE ON lab_test_models_requested_details (lab_test_model_id)');
        $this->addSql('CREATE TABLE lab_test_models (id SERIAL NOT NULL, created_by_id INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, code VARCHAR(255) NOT NULL, wording VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_F902AD1CB03A8386 ON lab_test_models (created_by_id)');
        $this->addSql('CREATE TABLE lab_tests_costs (id SERIAL NOT NULL, lab_test_id INT NOT NULL, created_by_id INT NOT NULL, unit_price DOUBLE PRECISION NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, is_actual BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_30EC75C972CE4932 ON lab_tests_costs (lab_test_id)');
        $this->addSql('CREATE INDEX IDX_30EC75C9B03A8386 ON lab_tests_costs (created_by_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_30EC75C972CE4932723417FB8B8E8428 ON lab_tests_costs (lab_test_id, is_actual, created_at)');
        $this->addSql('CREATE TABLE lab_test_requested_details (id SERIAL NOT NULL, lab_test_requested_id INT NOT NULL, lab_test_id INT NOT NULL, lab_test_cost_id INT NOT NULL, payment_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_F54B4DD15F734AD3 ON lab_test_requested_details (lab_test_requested_id)');
        $this->addSql('CREATE INDEX IDX_F54B4DD172CE4932 ON lab_test_requested_details (lab_test_id)');
        $this->addSql('CREATE INDEX IDX_F54B4DD1707FB509 ON lab_test_requested_details (lab_test_cost_id)');
        $this->addSql('CREATE INDEX IDX_F54B4DD14C3A3BB ON lab_test_requested_details (payment_id)');
        $this->addSql('CREATE TABLE health_parameters (id SERIAL NOT NULL, parameter_name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE consultation_categories (id SERIAL NOT NULL, created_by_id INT DEFAULT NULL, wording VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, code VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_43BC3A5B03A8386 ON consultation_categories (created_by_id)');
        $this->addSql('CREATE TABLE consultation_requested_details (id SERIAL NOT NULL, consultation_requested_id INT NOT NULL, consultation_category_id INT NOT NULL, consultation_category_cost_id INT NOT NULL, payment_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_9ACC45667BB0C4D3 ON consultation_requested_details (consultation_requested_id)');
        $this->addSql('CREATE INDEX IDX_9ACC4566F7ADEB6A ON consultation_requested_details (consultation_category_id)');
        $this->addSql('CREATE INDEX IDX_9ACC4566931BF9FA ON consultation_requested_details (consultation_category_cost_id)');
        $this->addSql('CREATE INDEX IDX_9ACC45664C3A3BB ON consultation_requested_details (payment_id)');
        $this->addSql('CREATE TABLE consultation_category_costs (id SERIAL NOT NULL, consultation_category_id INT NOT NULL, created_by_id INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, unit_price DOUBLE PRECISION NOT NULL, is_actual BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_E6B5B7BCF7ADEB6A ON consultation_category_costs (consultation_category_id)');
        $this->addSql('CREATE INDEX IDX_E6B5B7BCB03A8386 ON consultation_category_costs (created_by_id)');
        $this->addSql('CREATE TABLE validities_consultation (id SERIAL NOT NULL, period_validity INT NOT NULL, is_actual BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE consultations_requested (id SERIAL NOT NULL, patient_id INT NOT NULL, created_by_id INT NOT NULL, validity_period_id INT NOT NULL, reference VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, comment TEXT DEFAULT NULL, is_urgent BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_6780226F6B899279 ON consultations_requested (patient_id)');
        $this->addSql('CREATE INDEX IDX_6780226FB03A8386 ON consultations_requested (created_by_id)');
        $this->addSql('CREATE INDEX IDX_6780226F2CAC2C2 ON consultations_requested (validity_period_id)');
        $this->addSql('CREATE TABLE consultation_requested_parameters (id SERIAL NOT NULL, consultation_requested_id INT NOT NULL, health_parameter_id INT NOT NULL, value VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_884E083F7BB0C4D3 ON consultation_requested_parameters (consultation_requested_id)');
        $this->addSql('CREATE INDEX IDX_884E083FCBE9F44E ON consultation_requested_parameters (health_parameter_id)');
        $this->addSql('CREATE TABLE medicals_acts_categories (id SERIAL NOT NULL, created_by_id INT NOT NULL, wording VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_BC27CD50B03A8386 ON medicals_acts_categories (created_by_id)');
        $this->addSql('CREATE TABLE medicals_acts_requested (id SERIAL NOT NULL, patient_id INT NOT NULL, created_by_id INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, comment TEXT DEFAULT NULL, is_urgent BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_9F0BF77F6B899279 ON medicals_acts_requested (patient_id)');
        $this->addSql('CREATE INDEX IDX_9F0BF77FB03A8386 ON medicals_acts_requested (created_by_id)');
        $this->addSql('CREATE TABLE medical_act_requested_details (id SERIAL NOT NULL, medical_act_requested_id INT NOT NULL, medical_act_id INT NOT NULL, medical_act_cost_id INT NOT NULL, payment_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_C2A6ABB5AB4041F8 ON medical_act_requested_details (medical_act_requested_id)');
        $this->addSql('CREATE INDEX IDX_C2A6ABB5BAFBEC87 ON medical_act_requested_details (medical_act_id)');
        $this->addSql('CREATE INDEX IDX_C2A6ABB5F36EA167 ON medical_act_requested_details (medical_act_cost_id)');
        $this->addSql('CREATE INDEX IDX_C2A6ABB54C3A3BB ON medical_act_requested_details (payment_id)');
        $this->addSql('CREATE TABLE medicals_acts (id SERIAL NOT NULL, created_by_id INT NOT NULL, category_id INT NOT NULL, wording TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, code VARCHAR(255) NOT NULL, is_billable BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_72BD487177153098 ON medicals_acts (code)');
        $this->addSql('CREATE INDEX IDX_72BD4871B03A8386 ON medicals_acts (created_by_id)');
        $this->addSql('CREATE INDEX IDX_72BD487112469DE2 ON medicals_acts (category_id)');
        $this->addSql('CREATE TABLE medicals_acts_costs (id SERIAL NOT NULL, medical_act_id INT NOT NULL, created_by_id INT NOT NULL, unit_price DOUBLE PRECISION NOT NULL, is_actual BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_35B55CA1BAFBEC87 ON medicals_acts_costs (medical_act_id)');
        $this->addSql('CREATE INDEX IDX_35B55CA1B03A8386 ON medicals_acts_costs (created_by_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_35B55CA1BAFBEC87723417FB8B8E8428 ON medicals_acts_costs (medical_act_id, is_actual, created_at)');
        $this->addSql('CREATE TABLE drug_posologies (id SERIAL NOT NULL, drug_id INT NOT NULL, label VARCHAR(255) NOT NULL, explanation VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_7A50F923AABCA765 ON drug_posologies (drug_id)');
        $this->addSql('CREATE TABLE drug_requested_details (id SERIAL NOT NULL, drug_requested_id INT DEFAULT NULL, drug_id INT NOT NULL, drug_cost_id INT NOT NULL, payment_id INT DEFAULT NULL, quantity INT NOT NULL, comment TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_A4FE196F80165654 ON drug_requested_details (drug_requested_id)');
        $this->addSql('CREATE INDEX IDX_A4FE196FAABCA765 ON drug_requested_details (drug_id)');
        $this->addSql('CREATE INDEX IDX_A4FE196FD27863F0 ON drug_requested_details (drug_cost_id)');
        $this->addSql('CREATE INDEX IDX_A4FE196F4C3A3BB ON drug_requested_details (payment_id)');
        $this->addSql('CREATE TABLE drugs (id SERIAL NOT NULL, created_by_id INT NOT NULL, drug_form_id INT DEFAULT NULL, code VARCHAR(255) NOT NULL, wording VARCHAR(255) NOT NULL, packing VARCHAR(255) DEFAULT NULL, create_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_DA2C39DAB03A8386 ON drugs (created_by_id)');
        $this->addSql('CREATE INDEX IDX_DA2C39DA90317DF2 ON drugs (drug_form_id)');
        $this->addSql('CREATE TABLE drugs_requested (id SERIAL NOT NULL, patient_id INT NOT NULL, created_by_id INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, is_urgent BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_BE05F8A96B899279 ON drugs_requested (patient_id)');
        $this->addSql('CREATE INDEX IDX_BE05F8A9B03A8386 ON drugs_requested (created_by_id)');
        $this->addSql('CREATE TABLE drug_costs (id SERIAL NOT NULL, drug_id INT NOT NULL, created_by_id INT NOT NULL, unit_price DOUBLE PRECISION NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, is_actual BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_DB95D027AABCA765 ON drug_costs (drug_id)');
        $this->addSql('CREATE INDEX IDX_DB95D027B03A8386 ON drug_costs (created_by_id)');
        $this->addSql('CREATE TABLE drug_forms (id SERIAL NOT NULL, created_by_id INT NOT NULL, code VARCHAR(255) NOT NULL, wording VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_89B79C78B03A8386 ON drug_forms (created_by_id)');
        $this->addSql('ALTER TABLE emails ADD CONSTRAINT FK_4C81E852217BBB47 FOREIGN KEY (person_id) REFERENCES persons (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE emails ADD CONSTRAINT FK_4C81E852B03A8386 FOREIGN KEY (created_by_id) REFERENCES "users" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE persons ADD CONSTRAINT FK_A25CC7D35A2DB2A0 FOREIGN KEY (sex_id) REFERENCES sexes (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE persons ADD CONSTRAINT FK_A25CC7D3B03A8386 FOREIGN KEY (created_by_id) REFERENCES "users" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE persons ADD CONSTRAINT FK_A25CC7D323D6A298 FOREIGN KEY (civility_id) REFERENCES civilities (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE persons ADD CONSTRAINT FK_A25CC7D3E559F9BF FOREIGN KEY (marital_status_id) REFERENCES marital_status (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "users" ADD CONSTRAINT FK_1483A5E9217BBB47 FOREIGN KEY (person_id) REFERENCES persons (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE patients ADD CONSTRAINT FK_2CCC2E2C217BBB47 FOREIGN KEY (person_id) REFERENCES persons (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE patients ADD CONSTRAINT FK_2CCC2E2CB03A8386 FOREIGN KEY (created_by_id) REFERENCES "users" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE patients ADD CONSTRAINT FK_2CCC2E2C5F3AECE2 FOREIGN KEY (blood_group_id) REFERENCES blood_groups (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE cashiers ADD CONSTRAINT FK_EE44F633217BBB47 FOREIGN KEY (person_id) REFERENCES persons (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE cashiers ADD CONSTRAINT FK_EE44F633B03A8386 FOREIGN KEY (created_by_id) REFERENCES "users" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE nurses ADD CONSTRAINT FK_F409A14C217BBB47 FOREIGN KEY (person_id) REFERENCES persons (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE nurses ADD CONSTRAINT FK_F409A14C12469DE2 FOREIGN KEY (category_id) REFERENCES nurses_categories (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE nurses ADD CONSTRAINT FK_F409A14CB03A8386 FOREIGN KEY (created_by_id) REFERENCES "users" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE doctors ADD CONSTRAINT FK_B67687BE217BBB47 FOREIGN KEY (person_id) REFERENCES persons (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE doctors ADD CONSTRAINT FK_B67687BE12469DE2 FOREIGN KEY (category_id) REFERENCES doctors_categories (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE doctors ADD CONSTRAINT FK_B67687BEB03A8386 FOREIGN KEY (created_by_id) REFERENCES "users" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE others_staff ADD CONSTRAINT FK_F14D76FE217BBB47 FOREIGN KEY (person_id) REFERENCES persons (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE others_staff ADD CONSTRAINT FK_F14D76FEC0B27031 FOREIGN KEY (type_staff_id) REFERENCES others_types_staff (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE others_staff ADD CONSTRAINT FK_F14D76FEB03A8386 FOREIGN KEY (created_by_id) REFERENCES "users" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE technicians ADD CONSTRAINT FK_63FB4240217BBB47 FOREIGN KEY (person_id) REFERENCES persons (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE technicians ADD CONSTRAINT FK_63FB424012469DE2 FOREIGN KEY (category_id) REFERENCES technicians_categories (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE technicians ADD CONSTRAINT FK_63FB4240B03A8386 FOREIGN KEY (created_by_id) REFERENCES "users" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE phone_numbers ADD CONSTRAINT FK_E7DC46CB217BBB47 FOREIGN KEY (person_id) REFERENCES persons (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE phone_numbers ADD CONSTRAINT FK_E7DC46CBB03A8386 FOREIGN KEY (created_by_id) REFERENCES "users" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE first_names ADD CONSTRAINT FK_D3704F4A217BBB47 FOREIGN KEY (person_id) REFERENCES persons (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE first_names ADD CONSTRAINT FK_D3704F4AB03A8386 FOREIGN KEY (created_by_id) REFERENCES "users" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE identity_cards ADD CONSTRAINT FK_EE99120D217BBB47 FOREIGN KEY (person_id) REFERENCES persons (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE identity_cards ADD CONSTRAINT FK_EE99120DB03A8386 FOREIGN KEY (created_by_id) REFERENCES "users" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE payments ADD CONSTRAINT FK_65D29B32B03A8386 FOREIGN KEY (created_by_id) REFERENCES "users" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE advance_payments ADD CONSTRAINT FK_E098C60C4C3A3BB FOREIGN KEY (payment_id) REFERENCES payments (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE advance_payments ADD CONSTRAINT FK_E098C60CB03A8386 FOREIGN KEY (created_by_id) REFERENCES "users" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lab_tests_categories ADD CONSTRAINT FK_D645F012B03A8386 FOREIGN KEY (created_by_id) REFERENCES "users" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lab_tests ADD CONSTRAINT FK_75AC2A96B03A8386 FOREIGN KEY (created_by_id) REFERENCES "users" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lab_tests ADD CONSTRAINT FK_75AC2A9612469DE2 FOREIGN KEY (category_id) REFERENCES lab_tests_categories (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lab_tests_requested ADD CONSTRAINT FK_4D16476E6B899279 FOREIGN KEY (patient_id) REFERENCES patients (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lab_tests_requested ADD CONSTRAINT FK_4D16476EB03A8386 FOREIGN KEY (created_by_id) REFERENCES "users" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lab_tests_ranges ADD CONSTRAINT FK_2EB7118972CE4932 FOREIGN KEY (lab_test_id) REFERENCES lab_tests (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lab_tests_ranges ADD CONSTRAINT FK_2EB71189B03A8386 FOREIGN KEY (created_by_id) REFERENCES "users" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lab_test_model_rates ADD CONSTRAINT FK_E8515BB0C07EA3DE FOREIGN KEY (lab_test_model_id) REFERENCES lab_test_models (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lab_test_model_rates ADD CONSTRAINT FK_E8515BB0B03A8386 FOREIGN KEY (created_by_id) REFERENCES "users" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lab_test_models_requested ADD CONSTRAINT FK_4E74C6186B899279 FOREIGN KEY (patient_id) REFERENCES patients (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lab_test_models_requested ADD CONSTRAINT FK_4E74C618B03A8386 FOREIGN KEY (created_by_id) REFERENCES "users" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lab_test_models_requested ADD CONSTRAINT FK_4E74C61896121641 FOREIGN KEY (lab_test_model_rate_id) REFERENCES lab_test_model_rates (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lab_test_model_details ADD CONSTRAINT FK_58AD8254C07EA3DE FOREIGN KEY (lab_test_model_id) REFERENCES lab_test_models (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lab_test_model_details ADD CONSTRAINT FK_58AD8254B03A8386 FOREIGN KEY (created_by_id) REFERENCES "users" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lab_test_model_details ADD CONSTRAINT FK_58AD825472CE4932 FOREIGN KEY (lab_test_id) REFERENCES lab_tests (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lab_test_models_requested_details ADD CONSTRAINT FK_718DC327BCA92477 FOREIGN KEY (lab_test_model_requested_id) REFERENCES lab_test_models_requested (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lab_test_models_requested_details ADD CONSTRAINT FK_718DC327530FFA25 FOREIGN KEY (lab_test_model_detail_id) REFERENCES lab_test_model_details (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lab_test_models_requested_details ADD CONSTRAINT FK_718DC327707FB509 FOREIGN KEY (lab_test_cost_id) REFERENCES lab_tests_costs (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lab_test_models_requested_details ADD CONSTRAINT FK_718DC3274C3A3BB FOREIGN KEY (payment_id) REFERENCES payments (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lab_test_models_requested_details ADD CONSTRAINT FK_718DC327C07EA3DE FOREIGN KEY (lab_test_model_id) REFERENCES lab_test_models (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lab_test_models ADD CONSTRAINT FK_F902AD1CB03A8386 FOREIGN KEY (created_by_id) REFERENCES "users" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lab_tests_costs ADD CONSTRAINT FK_30EC75C972CE4932 FOREIGN KEY (lab_test_id) REFERENCES lab_tests (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lab_tests_costs ADD CONSTRAINT FK_30EC75C9B03A8386 FOREIGN KEY (created_by_id) REFERENCES "users" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lab_test_requested_details ADD CONSTRAINT FK_F54B4DD15F734AD3 FOREIGN KEY (lab_test_requested_id) REFERENCES lab_tests_requested (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lab_test_requested_details ADD CONSTRAINT FK_F54B4DD172CE4932 FOREIGN KEY (lab_test_id) REFERENCES lab_tests (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lab_test_requested_details ADD CONSTRAINT FK_F54B4DD1707FB509 FOREIGN KEY (lab_test_cost_id) REFERENCES lab_tests_costs (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lab_test_requested_details ADD CONSTRAINT FK_F54B4DD14C3A3BB FOREIGN KEY (payment_id) REFERENCES payments (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE consultation_categories ADD CONSTRAINT FK_43BC3A5B03A8386 FOREIGN KEY (created_by_id) REFERENCES "users" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE consultation_requested_details ADD CONSTRAINT FK_9ACC45667BB0C4D3 FOREIGN KEY (consultation_requested_id) REFERENCES consultations_requested (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE consultation_requested_details ADD CONSTRAINT FK_9ACC4566F7ADEB6A FOREIGN KEY (consultation_category_id) REFERENCES consultation_categories (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE consultation_requested_details ADD CONSTRAINT FK_9ACC4566931BF9FA FOREIGN KEY (consultation_category_cost_id) REFERENCES consultation_category_costs (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE consultation_requested_details ADD CONSTRAINT FK_9ACC45664C3A3BB FOREIGN KEY (payment_id) REFERENCES payments (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE consultation_category_costs ADD CONSTRAINT FK_E6B5B7BCF7ADEB6A FOREIGN KEY (consultation_category_id) REFERENCES consultation_categories (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE consultation_category_costs ADD CONSTRAINT FK_E6B5B7BCB03A8386 FOREIGN KEY (created_by_id) REFERENCES "users" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE consultations_requested ADD CONSTRAINT FK_6780226F6B899279 FOREIGN KEY (patient_id) REFERENCES patients (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE consultations_requested ADD CONSTRAINT FK_6780226FB03A8386 FOREIGN KEY (created_by_id) REFERENCES "users" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE consultations_requested ADD CONSTRAINT FK_6780226F2CAC2C2 FOREIGN KEY (validity_period_id) REFERENCES validities_consultation (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE consultation_requested_parameters ADD CONSTRAINT FK_884E083F7BB0C4D3 FOREIGN KEY (consultation_requested_id) REFERENCES consultations_requested (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE consultation_requested_parameters ADD CONSTRAINT FK_884E083FCBE9F44E FOREIGN KEY (health_parameter_id) REFERENCES health_parameters (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE medicals_acts_categories ADD CONSTRAINT FK_BC27CD50B03A8386 FOREIGN KEY (created_by_id) REFERENCES "users" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE medicals_acts_requested ADD CONSTRAINT FK_9F0BF77F6B899279 FOREIGN KEY (patient_id) REFERENCES patients (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE medicals_acts_requested ADD CONSTRAINT FK_9F0BF77FB03A8386 FOREIGN KEY (created_by_id) REFERENCES "users" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE medical_act_requested_details ADD CONSTRAINT FK_C2A6ABB5AB4041F8 FOREIGN KEY (medical_act_requested_id) REFERENCES medicals_acts_requested (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE medical_act_requested_details ADD CONSTRAINT FK_C2A6ABB5BAFBEC87 FOREIGN KEY (medical_act_id) REFERENCES medicals_acts (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE medical_act_requested_details ADD CONSTRAINT FK_C2A6ABB5F36EA167 FOREIGN KEY (medical_act_cost_id) REFERENCES medicals_acts_costs (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE medical_act_requested_details ADD CONSTRAINT FK_C2A6ABB54C3A3BB FOREIGN KEY (payment_id) REFERENCES payments (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE medicals_acts ADD CONSTRAINT FK_72BD4871B03A8386 FOREIGN KEY (created_by_id) REFERENCES "users" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE medicals_acts ADD CONSTRAINT FK_72BD487112469DE2 FOREIGN KEY (category_id) REFERENCES medicals_acts_categories (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE medicals_acts_costs ADD CONSTRAINT FK_35B55CA1BAFBEC87 FOREIGN KEY (medical_act_id) REFERENCES medicals_acts (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE medicals_acts_costs ADD CONSTRAINT FK_35B55CA1B03A8386 FOREIGN KEY (created_by_id) REFERENCES "users" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE drug_posologies ADD CONSTRAINT FK_7A50F923AABCA765 FOREIGN KEY (drug_id) REFERENCES drugs (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE drug_requested_details ADD CONSTRAINT FK_A4FE196F80165654 FOREIGN KEY (drug_requested_id) REFERENCES drugs_requested (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE drug_requested_details ADD CONSTRAINT FK_A4FE196FAABCA765 FOREIGN KEY (drug_id) REFERENCES drugs (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE drug_requested_details ADD CONSTRAINT FK_A4FE196FD27863F0 FOREIGN KEY (drug_cost_id) REFERENCES drug_costs (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE drug_requested_details ADD CONSTRAINT FK_A4FE196F4C3A3BB FOREIGN KEY (payment_id) REFERENCES payments (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE drugs ADD CONSTRAINT FK_DA2C39DAB03A8386 FOREIGN KEY (created_by_id) REFERENCES "users" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE drugs ADD CONSTRAINT FK_DA2C39DA90317DF2 FOREIGN KEY (drug_form_id) REFERENCES drug_forms (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE drugs_requested ADD CONSTRAINT FK_BE05F8A96B899279 FOREIGN KEY (patient_id) REFERENCES patients (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE drugs_requested ADD CONSTRAINT FK_BE05F8A9B03A8386 FOREIGN KEY (created_by_id) REFERENCES "users" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE drug_costs ADD CONSTRAINT FK_DB95D027AABCA765 FOREIGN KEY (drug_id) REFERENCES drugs (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE drug_costs ADD CONSTRAINT FK_DB95D027B03A8386 FOREIGN KEY (created_by_id) REFERENCES "users" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE drug_forms ADD CONSTRAINT FK_89B79C78B03A8386 FOREIGN KEY (created_by_id) REFERENCES "users" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'postgresql', 'Migration can only be executed safely on \'postgresql\'.');

        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE persons DROP CONSTRAINT FK_A25CC7D323D6A298');
        $this->addSql('ALTER TABLE persons DROP CONSTRAINT FK_A25CC7D3E559F9BF');
        $this->addSql('ALTER TABLE emails DROP CONSTRAINT FK_4C81E852217BBB47');
        $this->addSql('ALTER TABLE "users" DROP CONSTRAINT FK_1483A5E9217BBB47');
        $this->addSql('ALTER TABLE patients DROP CONSTRAINT FK_2CCC2E2C217BBB47');
        $this->addSql('ALTER TABLE cashiers DROP CONSTRAINT FK_EE44F633217BBB47');
        $this->addSql('ALTER TABLE nurses DROP CONSTRAINT FK_F409A14C217BBB47');
        $this->addSql('ALTER TABLE doctors DROP CONSTRAINT FK_B67687BE217BBB47');
        $this->addSql('ALTER TABLE others_staff DROP CONSTRAINT FK_F14D76FE217BBB47');
        $this->addSql('ALTER TABLE technicians DROP CONSTRAINT FK_63FB4240217BBB47');
        $this->addSql('ALTER TABLE phone_numbers DROP CONSTRAINT FK_E7DC46CB217BBB47');
        $this->addSql('ALTER TABLE first_names DROP CONSTRAINT FK_D3704F4A217BBB47');
        $this->addSql('ALTER TABLE identity_cards DROP CONSTRAINT FK_EE99120D217BBB47');
        $this->addSql('ALTER TABLE emails DROP CONSTRAINT FK_4C81E852B03A8386');
        $this->addSql('ALTER TABLE persons DROP CONSTRAINT FK_A25CC7D3B03A8386');
        $this->addSql('ALTER TABLE patients DROP CONSTRAINT FK_2CCC2E2CB03A8386');
        $this->addSql('ALTER TABLE cashiers DROP CONSTRAINT FK_EE44F633B03A8386');
        $this->addSql('ALTER TABLE nurses DROP CONSTRAINT FK_F409A14CB03A8386');
        $this->addSql('ALTER TABLE doctors DROP CONSTRAINT FK_B67687BEB03A8386');
        $this->addSql('ALTER TABLE others_staff DROP CONSTRAINT FK_F14D76FEB03A8386');
        $this->addSql('ALTER TABLE technicians DROP CONSTRAINT FK_63FB4240B03A8386');
        $this->addSql('ALTER TABLE phone_numbers DROP CONSTRAINT FK_E7DC46CBB03A8386');
        $this->addSql('ALTER TABLE first_names DROP CONSTRAINT FK_D3704F4AB03A8386');
        $this->addSql('ALTER TABLE identity_cards DROP CONSTRAINT FK_EE99120DB03A8386');
        $this->addSql('ALTER TABLE payments DROP CONSTRAINT FK_65D29B32B03A8386');
        $this->addSql('ALTER TABLE advance_payments DROP CONSTRAINT FK_E098C60CB03A8386');
        $this->addSql('ALTER TABLE lab_tests_categories DROP CONSTRAINT FK_D645F012B03A8386');
        $this->addSql('ALTER TABLE lab_tests DROP CONSTRAINT FK_75AC2A96B03A8386');
        $this->addSql('ALTER TABLE lab_tests_requested DROP CONSTRAINT FK_4D16476EB03A8386');
        $this->addSql('ALTER TABLE lab_tests_ranges DROP CONSTRAINT FK_2EB71189B03A8386');
        $this->addSql('ALTER TABLE lab_test_model_rates DROP CONSTRAINT FK_E8515BB0B03A8386');
        $this->addSql('ALTER TABLE lab_test_models_requested DROP CONSTRAINT FK_4E74C618B03A8386');
        $this->addSql('ALTER TABLE lab_test_model_details DROP CONSTRAINT FK_58AD8254B03A8386');
        $this->addSql('ALTER TABLE lab_test_models DROP CONSTRAINT FK_F902AD1CB03A8386');
        $this->addSql('ALTER TABLE lab_tests_costs DROP CONSTRAINT FK_30EC75C9B03A8386');
        $this->addSql('ALTER TABLE consultation_categories DROP CONSTRAINT FK_43BC3A5B03A8386');
        $this->addSql('ALTER TABLE consultation_category_costs DROP CONSTRAINT FK_E6B5B7BCB03A8386');
        $this->addSql('ALTER TABLE consultations_requested DROP CONSTRAINT FK_6780226FB03A8386');
        $this->addSql('ALTER TABLE medicals_acts_categories DROP CONSTRAINT FK_BC27CD50B03A8386');
        $this->addSql('ALTER TABLE medicals_acts_requested DROP CONSTRAINT FK_9F0BF77FB03A8386');
        $this->addSql('ALTER TABLE medicals_acts DROP CONSTRAINT FK_72BD4871B03A8386');
        $this->addSql('ALTER TABLE medicals_acts_costs DROP CONSTRAINT FK_35B55CA1B03A8386');
        $this->addSql('ALTER TABLE drugs DROP CONSTRAINT FK_DA2C39DAB03A8386');
        $this->addSql('ALTER TABLE drugs_requested DROP CONSTRAINT FK_BE05F8A9B03A8386');
        $this->addSql('ALTER TABLE drug_costs DROP CONSTRAINT FK_DB95D027B03A8386');
        $this->addSql('ALTER TABLE drug_forms DROP CONSTRAINT FK_89B79C78B03A8386');
        $this->addSql('ALTER TABLE persons DROP CONSTRAINT FK_A25CC7D35A2DB2A0');
        $this->addSql('ALTER TABLE patients DROP CONSTRAINT FK_2CCC2E2C5F3AECE2');
        $this->addSql('ALTER TABLE lab_tests_requested DROP CONSTRAINT FK_4D16476E6B899279');
        $this->addSql('ALTER TABLE lab_test_models_requested DROP CONSTRAINT FK_4E74C6186B899279');
        $this->addSql('ALTER TABLE consultations_requested DROP CONSTRAINT FK_6780226F6B899279');
        $this->addSql('ALTER TABLE medicals_acts_requested DROP CONSTRAINT FK_9F0BF77F6B899279');
        $this->addSql('ALTER TABLE drugs_requested DROP CONSTRAINT FK_BE05F8A96B899279');
        $this->addSql('ALTER TABLE nurses DROP CONSTRAINT FK_F409A14C12469DE2');
        $this->addSql('ALTER TABLE doctors DROP CONSTRAINT FK_B67687BE12469DE2');
        $this->addSql('ALTER TABLE others_staff DROP CONSTRAINT FK_F14D76FEC0B27031');
        $this->addSql('ALTER TABLE technicians DROP CONSTRAINT FK_63FB424012469DE2');
        $this->addSql('ALTER TABLE advance_payments DROP CONSTRAINT FK_E098C60C4C3A3BB');
        $this->addSql('ALTER TABLE lab_test_models_requested_details DROP CONSTRAINT FK_718DC3274C3A3BB');
        $this->addSql('ALTER TABLE lab_test_requested_details DROP CONSTRAINT FK_F54B4DD14C3A3BB');
        $this->addSql('ALTER TABLE consultation_requested_details DROP CONSTRAINT FK_9ACC45664C3A3BB');
        $this->addSql('ALTER TABLE medical_act_requested_details DROP CONSTRAINT FK_C2A6ABB54C3A3BB');
        $this->addSql('ALTER TABLE drug_requested_details DROP CONSTRAINT FK_A4FE196F4C3A3BB');
        $this->addSql('ALTER TABLE lab_tests DROP CONSTRAINT FK_75AC2A9612469DE2');
        $this->addSql('ALTER TABLE lab_tests_ranges DROP CONSTRAINT FK_2EB7118972CE4932');
        $this->addSql('ALTER TABLE lab_test_model_details DROP CONSTRAINT FK_58AD825472CE4932');
        $this->addSql('ALTER TABLE lab_tests_costs DROP CONSTRAINT FK_30EC75C972CE4932');
        $this->addSql('ALTER TABLE lab_test_requested_details DROP CONSTRAINT FK_F54B4DD172CE4932');
        $this->addSql('ALTER TABLE lab_test_requested_details DROP CONSTRAINT FK_F54B4DD15F734AD3');
        $this->addSql('ALTER TABLE lab_test_models_requested DROP CONSTRAINT FK_4E74C61896121641');
        $this->addSql('ALTER TABLE lab_test_models_requested_details DROP CONSTRAINT FK_718DC327BCA92477');
        $this->addSql('ALTER TABLE lab_test_models_requested_details DROP CONSTRAINT FK_718DC327530FFA25');
        $this->addSql('ALTER TABLE lab_test_model_rates DROP CONSTRAINT FK_E8515BB0C07EA3DE');
        $this->addSql('ALTER TABLE lab_test_model_details DROP CONSTRAINT FK_58AD8254C07EA3DE');
        $this->addSql('ALTER TABLE lab_test_models_requested_details DROP CONSTRAINT FK_718DC327C07EA3DE');
        $this->addSql('ALTER TABLE lab_test_models_requested_details DROP CONSTRAINT FK_718DC327707FB509');
        $this->addSql('ALTER TABLE lab_test_requested_details DROP CONSTRAINT FK_F54B4DD1707FB509');
        $this->addSql('ALTER TABLE consultation_requested_parameters DROP CONSTRAINT FK_884E083FCBE9F44E');
        $this->addSql('ALTER TABLE consultation_requested_details DROP CONSTRAINT FK_9ACC4566F7ADEB6A');
        $this->addSql('ALTER TABLE consultation_category_costs DROP CONSTRAINT FK_E6B5B7BCF7ADEB6A');
        $this->addSql('ALTER TABLE consultation_requested_details DROP CONSTRAINT FK_9ACC4566931BF9FA');
        $this->addSql('ALTER TABLE consultations_requested DROP CONSTRAINT FK_6780226F2CAC2C2');
        $this->addSql('ALTER TABLE consultation_requested_details DROP CONSTRAINT FK_9ACC45667BB0C4D3');
        $this->addSql('ALTER TABLE consultation_requested_parameters DROP CONSTRAINT FK_884E083F7BB0C4D3');
        $this->addSql('ALTER TABLE medicals_acts DROP CONSTRAINT FK_72BD487112469DE2');
        $this->addSql('ALTER TABLE medical_act_requested_details DROP CONSTRAINT FK_C2A6ABB5AB4041F8');
        $this->addSql('ALTER TABLE medical_act_requested_details DROP CONSTRAINT FK_C2A6ABB5BAFBEC87');
        $this->addSql('ALTER TABLE medicals_acts_costs DROP CONSTRAINT FK_35B55CA1BAFBEC87');
        $this->addSql('ALTER TABLE medical_act_requested_details DROP CONSTRAINT FK_C2A6ABB5F36EA167');
        $this->addSql('ALTER TABLE drug_posologies DROP CONSTRAINT FK_7A50F923AABCA765');
        $this->addSql('ALTER TABLE drug_requested_details DROP CONSTRAINT FK_A4FE196FAABCA765');
        $this->addSql('ALTER TABLE drug_costs DROP CONSTRAINT FK_DB95D027AABCA765');
        $this->addSql('ALTER TABLE drug_requested_details DROP CONSTRAINT FK_A4FE196F80165654');
        $this->addSql('ALTER TABLE drug_requested_details DROP CONSTRAINT FK_A4FE196FD27863F0');
        $this->addSql('ALTER TABLE drugs DROP CONSTRAINT FK_DA2C39DA90317DF2');
        $this->addSql('DROP TABLE emails');
        $this->addSql('DROP TABLE civilities');
        $this->addSql('DROP TABLE marital_status');
        $this->addSql('DROP TABLE persons');
        $this->addSql('DROP TABLE "users"');
        $this->addSql('DROP TABLE sexes');
        $this->addSql('DROP TABLE blood_groups');
        $this->addSql('DROP TABLE patients');
        $this->addSql('DROP TABLE cashiers');
        $this->addSql('DROP TABLE nurses_categories');
        $this->addSql('DROP TABLE nurses');
        $this->addSql('DROP TABLE doctors');
        $this->addSql('DROP TABLE doctors_categories');
        $this->addSql('DROP TABLE others_types_staff');
        $this->addSql('DROP TABLE others_staff');
        $this->addSql('DROP TABLE technicians_categories');
        $this->addSql('DROP TABLE technicians');
        $this->addSql('DROP TABLE phone_numbers');
        $this->addSql('DROP TABLE first_names');
        $this->addSql('DROP TABLE identity_cards');
        $this->addSql('DROP TABLE payments');
        $this->addSql('DROP TABLE advance_payments');
        $this->addSql('DROP TABLE lab_tests_categories');
        $this->addSql('DROP TABLE lab_tests');
        $this->addSql('DROP TABLE lab_tests_requested');
        $this->addSql('DROP TABLE lab_tests_ranges');
        $this->addSql('DROP TABLE lab_test_model_rates');
        $this->addSql('DROP TABLE lab_test_models_requested');
        $this->addSql('DROP TABLE lab_test_model_details');
        $this->addSql('DROP TABLE lab_test_models_requested_details');
        $this->addSql('DROP TABLE lab_test_models');
        $this->addSql('DROP TABLE lab_tests_costs');
        $this->addSql('DROP TABLE lab_test_requested_details');
        $this->addSql('DROP TABLE health_parameters');
        $this->addSql('DROP TABLE consultation_categories');
        $this->addSql('DROP TABLE consultation_requested_details');
        $this->addSql('DROP TABLE consultation_category_costs');
        $this->addSql('DROP TABLE validities_consultation');
        $this->addSql('DROP TABLE consultations_requested');
        $this->addSql('DROP TABLE consultation_requested_parameters');
        $this->addSql('DROP TABLE medicals_acts_categories');
        $this->addSql('DROP TABLE medicals_acts_requested');
        $this->addSql('DROP TABLE medical_act_requested_details');
        $this->addSql('DROP TABLE medicals_acts');
        $this->addSql('DROP TABLE medicals_acts_costs');
        $this->addSql('DROP TABLE drug_posologies');
        $this->addSql('DROP TABLE drug_requested_details');
        $this->addSql('DROP TABLE drugs');
        $this->addSql('DROP TABLE drugs_requested');
        $this->addSql('DROP TABLE drug_costs');
        $this->addSql('DROP TABLE drug_forms');
    }
}
